### PR TITLE
refactor: editor bubble menu and its extensions

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

此 PR 重构了编辑器冒泡菜单，之后冒泡菜单的声明及创建可与组件 DOM 分离，并且本 PR 优化了菜单的样式及表现。
现在冒泡菜单不再响应移向目标组件的事件而改为点击某个组件出现，这更加符合编辑操作和体验，也不会出现类似于 https://github.com/halo-dev/halo/issues/3208 的无法选中的问题。且此次修改向下兼容，若插件使用旧版本的冒泡菜单则不会受到影响。

before:
image

after:
image

todo:
- [x] 代码编写
- [x] 更新旧冒泡菜单
- [x] 优化调整
- [x] 扩展文档

#### How to test it?

查看编辑器各块元素的冒泡菜单功能是否正常。

#### Does this PR introduce a user-facing change?
```release-note
重构编辑器冒泡菜单
```

### CODE REVIEW

**Comment by LIlGG** [comment]
/retitle refactor: editor bubble menu and its extensions

**Review by JohnNiang — COMMENTED** [review]
It works very well.

image

**Pull request merged**
