### PR TITLE
feat: New Katex Plugin, Supporting Markdown Input Rule,And Katex Inline,Katex Block

### PR DESCRIPTION
**Pull request by xinkeng0**
from #10 

This PR only provides a minimal implementation of the Katex plugin in the example, and the Official Plugin that conforms to Halo is pending the author's processing.

The HTML exported by the plugin currently requires the end user to use the Katex or Mathjax library for rendering.
> In this regard, examples such as Hexo(like this) and Yuque( use svg) have been examined, and they have also implemented similar approaches. Therefore, rendered HTML is not exported.

```release-note
提供 Katex 插件的最小实现
```

### CODE REVIEW

**Comment by ruibaby** [comment]
Hi @gengxiaoxiaoxin , is there any update? I noticed that it is still in draft status. Do you need any assistance?

**Comment by xinkeng0** [comment]
> Hi @gengxiaoxiaoxin , is there any update? I noticed that it is still in draft status. Do you need any assistance?

Hi @ruibaby ,
It should now be available in other themes with the help of Katex.js. There may still be a need for some final polishing of the details.

As for the "direct output of KatexRenderedHTML" issue, i'm still considering it.

**Comment by ruibaby** [comment]
cc @halo-sigs/halo

**Comment by ruibaby** [comment]
Hi @gengxiaoxiaoxin 

Sorry for the late reply, I tested with the latest code and found that the example seems to be missing two packages (@tiptap/vue-3 and katex), which is causing it to not run properly. Also, why is katex support placed in the example's draft folder? Is this PR ready for review?

> In this regard, examples such as Hexo(like this) and Yuque( use svg) have been examined, and they have also implemented similar approaches. Therefore, rendered HTML is not exported.

If we want to provide out-of-the-box KaTeX support for the end users, it seems we can wait until https://github.com/halo-dev/halo/issues/4003 is completed. Additionally, can we consider supporting KaTeX as a plugin? Because this editor will also support being extended.

**Comment by xinkeng0** [comment]
Hi @ruibaby 
> Sorry for the late reply, I tested with the latest code and found that the example seems to be missing two packages (@tiptap/vue-3 and katex), which is causing it to not run properly. Also, why is katex support placed in the example's draft folder? Is this PR ready for review?

The missing package has been added (seems to be related to my initial use of pnpm8 locally)

> If we want to provide out-of-the-box KaTeX support for the end users, it seems we can wait until https://github.com/halo-dev/halo/issues/4003 is completed. Additionally, can we consider supporting KaTeX as a plugin? Because this editor will also support being extended.

Great, I also think the current appearance of the plugin is too simple. Let's continue discussing the future of this plugin after https://github.com/halo-dev/halo/issues/4003 is completed.

**Comment by ruibaby** [comment]
> Great, I also think the current appearance of the plugin is too simple. Let's continue discussing the future of this plugin after https://github.com/halo-dev/halo/issues/4003 is completed.

this is my summary of what can be done after 2.7.0:

1. Halo Console supports extending the editor via plugins.
2. The editor needs some refactoring to make Halo extensions easier, including but not limited to Extension, Slash Commands Items, and Toolbar Items.
3. Halo Core provides extension points for intercepting and processing post content.
4. After completing the above, we can create a "plugin-katex" project, which allows users to use Katex syntax in the editor and render it in the post when the plugin is installed.

BTW, Welcome to participate in the discussion and implementation. 🚀

**Pull request closed without merging**
