### PR TITLE
feat: Revert the changes made in #2 to support ImageViewResizing.

### LINKED ISSUE #8: feat: Revert the changes made in #2 to support ImageViewResizing.
Revert the changes made in #2.
Avoid conflicts with manual size setting caused by immediate triggering after binding by checking the number of ResizeObserver events triggered.
Remove the transition of the Image component (or at least remove the width and height) to avoid the blocking feeling caused by resizing.
The example has been updated accordingly. You can clone this repository to verify.

https://github.com/gengxiaoxiaoxin/richtext-editor

If the review passes, I would be happy to submit a PR.

image
image

### PR DESCRIPTION
**Pull request by xinkeng0**
PR from #8 
Revert the changes made in https://github.com/halo-sigs/richtext-editor/pull/2.
Avoid conflicts with manual size setting caused by immediate triggering after binding by checking the number of ResizeObserver events triggered.
Remove the transition of the Image component (or at least remove the width and height) to avoid the blocking feeling caused by resizing.

~~This PR has changed the example-package.json,But the pack lock file was not submitted.(I have an inconsistent version of PNPM)~~

Fixes #8 

```release-note
支持拖拽调整图片大小。
```

### CODE REVIEW

**Comment by ruibaby** [comment]
> This PR has changed the example-package.json,But the pack lock file was not submitted.(I have an inconsistent version of PNPM)

you can try this:

```
npx pnpm@7 install
```

**Comment by xinkeng0** [comment]
Updated.

**Review by ruibaby — COMMENTED** [review]
/lgtm

Thanks for your first contribution！

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Review by ruibaby — APPROVED** [review]
/lgtm

**Pull request merged**
